/*
 * generated by Xtext 2.36.0
 */
package no.ntnu.tdt4250.g07.bg.bgdl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBoardGameDLScopeProvider extends DelegatingScopeProvider {
}
