<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bg" nsURI="http://www.example.org/bg" nsPrefix="bg">
  <eClassifiers xsi:type="ecore:EClass" name="BoardGame">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="piecetypes" lowerBound="1"
        upperBound="-1" eType="#//PieceType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellstate" upperBound="-1"
        eType="#//CellState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="wincondition" lowerBound="1"
        upperBound="-1" eType="#//WinCondition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PieceType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="validmove" lowerBound="1"
        upperBound="-1" eType="#//ValidMove" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effectoncell" upperBound="-1"
        eType="#//EffectOnCell" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidMove">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" upperBound="-1"
        eType="#//Condition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeAnywhere" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellstate" upperBound="-1"
        eType="#//CellState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CellState"/>
  <eClassifiers xsi:type="ecore:EClass" name="EffectOnCell">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cellstate" lowerBound="1"
        eType="#//CellState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WinCondition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inarow" lowerBound="1"
        eType="#//InARow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InARow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagonal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="horizontal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vertical" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
