/**
 * generated by Xtext 2.35.0
 */
package no.ntnu.tdt4250.g07.bg.bgdl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import no.ntnu.tdt4250.g07.bg.bgdl.services.BoardgameDLGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class BoardgameDLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private BoardgameDLGrammarAccess _boardgameDLGrammarAccess;

  protected void _format(final /* Rules */Object rules, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nboard cannot be resolved"
      + "\nformat cannot be resolved");
  }

  protected void _format(final /* Board */Object board, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nplayerbrickset cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nvalidmove cannot be resolved"
      + "\nformat cannot be resolved");
  }

  public void format(final Object rules, final IFormattableDocument document) {
    if (rules instanceof XtextResource) {
      _format((XtextResource)rules, document);
      return;
    } else if (rules instanceof EObject) {
      _format((EObject)rules, document);
      return;
    } else if (rules == null) {
      _format((Void)null, document);
      return;
    } else if (rules != null) {
      _format(rules, document);
      return;
    } else if (rules != null) {
      _format(rules, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(rules, document).toString());
    }
  }
}
