/*
 * generated by Xtext 2.35.0
 */
package no.ntnu.tdt4250.g07.bg.bgdl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BoardgameDLStandaloneSetup extends BoardgameDLStandaloneSetupGenerated {

	public static void doSetup() {
		new BoardgameDLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
