/*
 * generated by Xtext 2.35.0
 */
package no.ntnu.tdt4250.g07.bg.bgdl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import no.ntnu.tdt4250.g07.bg.bgdl.BoardgameDLRuntimeModule;
import no.ntnu.tdt4250.g07.bg.bgdl.BoardgameDLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BoardgameDLIdeSetup extends BoardgameDLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BoardgameDLRuntimeModule(), new BoardgameDLIdeModule()));
	}
	
}
