/*
 * generated by Xtext
 */
package no.ntnu.tdt4250.g07.bg.bgdl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BoardGameDLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class BoardGameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.BoardGame");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTitleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cBoardSizeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSizeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSizeEIntParserRuleCall_3_0 = (RuleCall)cSizeAssignment_3.eContents().get(0);
		private final Keyword cPieceTypesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPiecetypesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPiecetypesPieceTypeParserRuleCall_6_0 = (RuleCall)cPiecetypesAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPiecetypesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPiecetypesPieceTypeParserRuleCall_7_1_0 = (RuleCall)cPiecetypesAssignment_7_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCellStatesKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cCellstatesAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cCellstatesCellStateParserRuleCall_9_2_0 = (RuleCall)cCellstatesAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cCellstatesAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cCellstatesCellStateParserRuleCall_9_3_1_0 = (RuleCall)cCellstatesAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Keyword cWinConditionsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cLeftSquareBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cWinConditionsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cWinConditionsWinConditionParserRuleCall_12_0 = (RuleCall)cWinConditionsAssignment_12.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cCommaKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cWinConditionsAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cWinConditionsWinConditionParserRuleCall_13_1_0 = (RuleCall)cWinConditionsAssignment_13_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//BoardGame returns BoardGame:
		//    'Title' (name = EString)
		//    'BoardSize' size=EInt
		//    'pieceTypes' '['piecetypes+=PieceType ( "," piecetypes+=PieceType)* ']'
		//    ('cellStates' '['cellstates+=CellState ( "," cellstates+=CellState)*']' )?
		//    'winConditions' '[' winConditions+=WinCondition ( "," winConditions+=WinCondition)* ']'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'Title' (name = EString)
		//'BoardSize' size=EInt
		//'pieceTypes' '['piecetypes+=PieceType ( "," piecetypes+=PieceType)* ']'
		//('cellStates' '['cellstates+=CellState ( "," cellstates+=CellState)*']' )?
		//'winConditions' '[' winConditions+=WinCondition ( "," winConditions+=WinCondition)* ']'
		public Group getGroup() { return cGroup; }
		
		//'Title'
		public Keyword getTitleKeyword_0() { return cTitleKeyword_0; }
		
		//(name = EString)
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'BoardSize'
		public Keyword getBoardSizeKeyword_2() { return cBoardSizeKeyword_2; }
		
		//size=EInt
		public Assignment getSizeAssignment_3() { return cSizeAssignment_3; }
		
		//EInt
		public RuleCall getSizeEIntParserRuleCall_3_0() { return cSizeEIntParserRuleCall_3_0; }
		
		//'pieceTypes'
		public Keyword getPieceTypesKeyword_4() { return cPieceTypesKeyword_4; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5() { return cLeftSquareBracketKeyword_5; }
		
		//piecetypes+=PieceType
		public Assignment getPiecetypesAssignment_6() { return cPiecetypesAssignment_6; }
		
		//PieceType
		public RuleCall getPiecetypesPieceTypeParserRuleCall_6_0() { return cPiecetypesPieceTypeParserRuleCall_6_0; }
		
		//( "," piecetypes+=PieceType)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//piecetypes+=PieceType
		public Assignment getPiecetypesAssignment_7_1() { return cPiecetypesAssignment_7_1; }
		
		//PieceType
		public RuleCall getPiecetypesPieceTypeParserRuleCall_7_1_0() { return cPiecetypesPieceTypeParserRuleCall_7_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_8() { return cRightSquareBracketKeyword_8; }
		
		//('cellStates' '['cellstates+=CellState ( "," cellstates+=CellState)*']' )?
		public Group getGroup_9() { return cGroup_9; }
		
		//'cellStates'
		public Keyword getCellStatesKeyword_9_0() { return cCellStatesKeyword_9_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_9_1() { return cLeftSquareBracketKeyword_9_1; }
		
		//cellstates+=CellState
		public Assignment getCellstatesAssignment_9_2() { return cCellstatesAssignment_9_2; }
		
		//CellState
		public RuleCall getCellstatesCellStateParserRuleCall_9_2_0() { return cCellstatesCellStateParserRuleCall_9_2_0; }
		
		//( "," cellstates+=CellState)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//cellstates+=CellState
		public Assignment getCellstatesAssignment_9_3_1() { return cCellstatesAssignment_9_3_1; }
		
		//CellState
		public RuleCall getCellstatesCellStateParserRuleCall_9_3_1_0() { return cCellstatesCellStateParserRuleCall_9_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_9_4() { return cRightSquareBracketKeyword_9_4; }
		
		//'winConditions'
		public Keyword getWinConditionsKeyword_10() { return cWinConditionsKeyword_10; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_11() { return cLeftSquareBracketKeyword_11; }
		
		//winConditions+=WinCondition
		public Assignment getWinConditionsAssignment_12() { return cWinConditionsAssignment_12; }
		
		//WinCondition
		public RuleCall getWinConditionsWinConditionParserRuleCall_12_0() { return cWinConditionsWinConditionParserRuleCall_12_0; }
		
		//( "," winConditions+=WinCondition)*
		public Group getGroup_13() { return cGroup_13; }
		
		//","
		public Keyword getCommaKeyword_13_0() { return cCommaKeyword_13_0; }
		
		//winConditions+=WinCondition
		public Assignment getWinConditionsAssignment_13_1() { return cWinConditionsAssignment_13_1; }
		
		//WinCondition
		public RuleCall getWinConditionsWinConditionParserRuleCall_13_1_0() { return cWinConditionsWinConditionParserRuleCall_13_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_14() { return cRightSquareBracketKeyword_14; }
	}
	public class PieceTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.PieceType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPieceTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSymbolKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSymbolAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSymbolEStringParserRuleCall_3_0 = (RuleCall)cSymbolAssignment_3.eContents().get(0);
		private final Keyword cHasValidMovesWhenKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cValidmovesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cValidmovesValidMoveParserRuleCall_6_0 = (RuleCall)cValidmovesAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cValidmovesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cValidmovesValidMoveParserRuleCall_7_1_0 = (RuleCall)cValidmovesAssignment_7_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cHasEffectOnCellKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cEffectsoncellAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cEffectsoncellEffectOnCellParserRuleCall_9_2_0 = (RuleCall)cEffectsoncellAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cEffectsoncellAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cEffectsoncellEffectOnCellParserRuleCall_9_3_1_0 = (RuleCall)cEffectsoncellAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		
		//PieceType returns PieceType:
		//    'PieceType'
		//    name=EString
		//        'Symbol' symbol=EString
		//        'hasValidMovesWhen' '[' validmoves+=ValidMove ( "," validmoves+=ValidMove)* ']'
		//        ('hasEffectOnCell' '[' effectsoncell+=EffectOnCell ( "," effectsoncell+=EffectOnCell)* ']' )?;
		@Override public ParserRule getRule() { return rule; }
		
		//'PieceType'
		//name=EString
		//    'Symbol' symbol=EString
		//    'hasValidMovesWhen' '[' validmoves+=ValidMove ( "," validmoves+=ValidMove)* ']'
		//    ('hasEffectOnCell' '[' effectsoncell+=EffectOnCell ( "," effectsoncell+=EffectOnCell)* ']' )?
		public Group getGroup() { return cGroup; }
		
		//'PieceType'
		public Keyword getPieceTypeKeyword_0() { return cPieceTypeKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'Symbol'
		public Keyword getSymbolKeyword_2() { return cSymbolKeyword_2; }
		
		//symbol=EString
		public Assignment getSymbolAssignment_3() { return cSymbolAssignment_3; }
		
		//EString
		public RuleCall getSymbolEStringParserRuleCall_3_0() { return cSymbolEStringParserRuleCall_3_0; }
		
		//'hasValidMovesWhen'
		public Keyword getHasValidMovesWhenKeyword_4() { return cHasValidMovesWhenKeyword_4; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5() { return cLeftSquareBracketKeyword_5; }
		
		//validmoves+=ValidMove
		public Assignment getValidmovesAssignment_6() { return cValidmovesAssignment_6; }
		
		//ValidMove
		public RuleCall getValidmovesValidMoveParserRuleCall_6_0() { return cValidmovesValidMoveParserRuleCall_6_0; }
		
		//( "," validmoves+=ValidMove)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//validmoves+=ValidMove
		public Assignment getValidmovesAssignment_7_1() { return cValidmovesAssignment_7_1; }
		
		//ValidMove
		public RuleCall getValidmovesValidMoveParserRuleCall_7_1_0() { return cValidmovesValidMoveParserRuleCall_7_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_8() { return cRightSquareBracketKeyword_8; }
		
		//('hasEffectOnCell' '[' effectsoncell+=EffectOnCell ( "," effectsoncell+=EffectOnCell)* ']' )?
		public Group getGroup_9() { return cGroup_9; }
		
		//'hasEffectOnCell'
		public Keyword getHasEffectOnCellKeyword_9_0() { return cHasEffectOnCellKeyword_9_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_9_1() { return cLeftSquareBracketKeyword_9_1; }
		
		//effectsoncell+=EffectOnCell
		public Assignment getEffectsoncellAssignment_9_2() { return cEffectsoncellAssignment_9_2; }
		
		//EffectOnCell
		public RuleCall getEffectsoncellEffectOnCellParserRuleCall_9_2_0() { return cEffectsoncellEffectOnCellParserRuleCall_9_2_0; }
		
		//( "," effectsoncell+=EffectOnCell)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//effectsoncell+=EffectOnCell
		public Assignment getEffectsoncellAssignment_9_3_1() { return cEffectsoncellAssignment_9_3_1; }
		
		//EffectOnCell
		public RuleCall getEffectsoncellEffectOnCellParserRuleCall_9_3_1_0() { return cEffectsoncellEffectOnCellParserRuleCall_9_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_9_4() { return cRightSquareBracketKeyword_9_4; }
	}
	public class CellStateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.CellState");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//CellState returns CellState:
		//    name=ID
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class WinConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.WinCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInARowKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cInarowAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInarowInARowParserRuleCall_1_0 = (RuleCall)cInarowAssignment_1.eContents().get(0);
		
		//WinCondition returns WinCondition:
		//        'InARow' inarow=InARow;
		@Override public ParserRule getRule() { return rule; }
		
		//'InARow' inarow=InARow
		public Group getGroup() { return cGroup; }
		
		//'InARow'
		public Keyword getInARowKeyword_0() { return cInARowKeyword_0; }
		
		//inarow=InARow
		public Assignment getInarowAssignment_1() { return cInarowAssignment_1; }
		
		//InARow
		public RuleCall getInarowInARowParserRuleCall_1_0() { return cInarowInARowParserRuleCall_1_0; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ValidMoveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.ValidMove");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cValidMoveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPlaceAnywhereAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cPlaceAnywherePlaceAnywhereKeyword_2_0 = (Keyword)cPlaceAnywhereAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cWhenKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cConditionsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cConditionsConditionParserRuleCall_3_1_0 = (RuleCall)cConditionsAssignment_3_1.eContents().get(0);
		private final Group cGroup_3_2 = (Group)cGroup_3.eContents().get(2);
		private final Keyword cAndKeyword_3_2_0 = (Keyword)cGroup_3_2.eContents().get(0);
		private final Assignment cConditionsAssignment_3_2_1 = (Assignment)cGroup_3_2.eContents().get(1);
		private final RuleCall cConditionsConditionParserRuleCall_3_2_1_0 = (RuleCall)cConditionsAssignment_3_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ValidMove returns ValidMove:
		//    'ValidMove'
		//    '{'
		//        placeAnywhere?='placeAnywhere'
		//        ('when' conditions+=Condition ( "and" conditions+=Condition)* )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ValidMove'
		//'{'
		//    placeAnywhere?='placeAnywhere'
		//    ('when' conditions+=Condition ( "and" conditions+=Condition)* )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ValidMove'
		public Keyword getValidMoveKeyword_0() { return cValidMoveKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//placeAnywhere?='placeAnywhere'
		public Assignment getPlaceAnywhereAssignment_2() { return cPlaceAnywhereAssignment_2; }
		
		//'placeAnywhere'
		public Keyword getPlaceAnywherePlaceAnywhereKeyword_2_0() { return cPlaceAnywherePlaceAnywhereKeyword_2_0; }
		
		//('when' conditions+=Condition ( "and" conditions+=Condition)* )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'when'
		public Keyword getWhenKeyword_3_0() { return cWhenKeyword_3_0; }
		
		//conditions+=Condition
		public Assignment getConditionsAssignment_3_1() { return cConditionsAssignment_3_1; }
		
		//Condition
		public RuleCall getConditionsConditionParserRuleCall_3_1_0() { return cConditionsConditionParserRuleCall_3_1_0; }
		
		//( "and" conditions+=Condition)*
		public Group getGroup_3_2() { return cGroup_3_2; }
		
		//"and"
		public Keyword getAndKeyword_3_2_0() { return cAndKeyword_3_2_0; }
		
		//conditions+=Condition
		public Assignment getConditionsAssignment_3_2_1() { return cConditionsAssignment_3_2_1; }
		
		//Condition
		public RuleCall getConditionsConditionParserRuleCall_3_2_1_0() { return cConditionsConditionParserRuleCall_3_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EffectOnCellElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.EffectOnCell");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEffectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRelativePositionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cXAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cXEIntParserRuleCall_5_0 = (RuleCall)cXAssignment_5.eContents().get(0);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cYAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cYEIntParserRuleCall_7_0 = (RuleCall)cYAssignment_7.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cNewCellStateKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cLeftParenthesisKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cCellstateAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final CrossReference cCellstateCellStateCrossReference_11_0 = (CrossReference)cCellstateAssignment_11.eContents().get(0);
		private final RuleCall cCellstateCellStateEStringParserRuleCall_11_0_1 = (RuleCall)cCellstateCellStateCrossReference_11_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cRightParenthesisKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//EffectOnCell returns EffectOnCell:
		//    'effect' '->' '('
		//        'relativePosition' '('x=EInt','y=EInt')'
		//        'newCellState''('cellstate=[CellState|EString]')' ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'effect' '->' '('
		//    'relativePosition' '('x=EInt','y=EInt')'
		//    'newCellState''('cellstate=[CellState|EString]')' ')'
		public Group getGroup() { return cGroup; }
		
		//'effect'
		public Keyword getEffectKeyword_0() { return cEffectKeyword_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_1() { return cHyphenMinusGreaterThanSignKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//'relativePosition'
		public Keyword getRelativePositionKeyword_3() { return cRelativePositionKeyword_3; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//x=EInt
		public Assignment getXAssignment_5() { return cXAssignment_5; }
		
		//EInt
		public RuleCall getXEIntParserRuleCall_5_0() { return cXEIntParserRuleCall_5_0; }
		
		//','
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
		
		//y=EInt
		public Assignment getYAssignment_7() { return cYAssignment_7; }
		
		//EInt
		public RuleCall getYEIntParserRuleCall_7_0() { return cYEIntParserRuleCall_7_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
		
		//'newCellState'
		public Keyword getNewCellStateKeyword_9() { return cNewCellStateKeyword_9; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_10() { return cLeftParenthesisKeyword_10; }
		
		//cellstate=[CellState|EString]
		public Assignment getCellstateAssignment_11() { return cCellstateAssignment_11; }
		
		//[CellState|EString]
		public CrossReference getCellstateCellStateCrossReference_11_0() { return cCellstateCellStateCrossReference_11_0; }
		
		//EString
		public RuleCall getCellstateCellStateEStringParserRuleCall_11_0_1() { return cCellstateCellStateEStringParserRuleCall_11_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_12() { return cRightParenthesisKeyword_12; }
		
		//')'
		public Keyword getRightParenthesisKeyword_13() { return cRightParenthesisKeyword_13; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.Condition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCellstateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cCellstateAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cCellstateCellStateCrossReference_2_0 = (CrossReference)cCellstateAssignment_2.eContents().get(0);
		private final RuleCall cCellstateCellStateEStringParserRuleCall_2_0_1 = (RuleCall)cCellstateCellStateCrossReference_2_0.eContents().get(1);
		
		//Condition returns Condition:
		//        'cellstate' '->' cellstate=[CellState|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//'cellstate' '->' cellstate=[CellState|EString]
		public Group getGroup() { return cGroup; }
		
		//'cellstate'
		public Keyword getCellstateKeyword_0() { return cCellstateKeyword_0; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_1() { return cHyphenMinusGreaterThanSignKeyword_1; }
		
		//cellstate=[CellState|EString]
		public Assignment getCellstateAssignment_2() { return cCellstateAssignment_2; }
		
		//[CellState|EString]
		public CrossReference getCellstateCellStateCrossReference_2_0() { return cCellstateCellStateCrossReference_2_0; }
		
		//EString
		public RuleCall getCellstateCellStateEStringParserRuleCall_2_0_1() { return cCellstateCellStateEStringParserRuleCall_2_0_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class InARowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL.InARow");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cHorizontalAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cHorizontalHorizontalKeyword_0_0 = (Keyword)cHorizontalAssignment_0.eContents().get(0);
		private final Assignment cVerticalAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cVerticalVerticalKeyword_1_0 = (Keyword)cVerticalAssignment_1.eContents().get(0);
		private final Assignment cDiagonalAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cDiagonalDiagonalKeyword_2_0 = (Keyword)cDiagonalAssignment_2.eContents().get(0);
		private final Keyword cCountKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCountAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCountEIntParserRuleCall_4_0 = (RuleCall)cCountAssignment_4.eContents().get(0);
		
		//InARow returns InARow:
		//    horizontal?='horizontal'
		//    vertical?='vertical'
		//    diagonal?='diagonal'
		//    'count' count=EInt;
		@Override public ParserRule getRule() { return rule; }
		
		//horizontal?='horizontal'
		//vertical?='vertical'
		//diagonal?='diagonal'
		//'count' count=EInt
		public Group getGroup() { return cGroup; }
		
		//horizontal?='horizontal'
		public Assignment getHorizontalAssignment_0() { return cHorizontalAssignment_0; }
		
		//'horizontal'
		public Keyword getHorizontalHorizontalKeyword_0_0() { return cHorizontalHorizontalKeyword_0_0; }
		
		//vertical?='vertical'
		public Assignment getVerticalAssignment_1() { return cVerticalAssignment_1; }
		
		//'vertical'
		public Keyword getVerticalVerticalKeyword_1_0() { return cVerticalVerticalKeyword_1_0; }
		
		//diagonal?='diagonal'
		public Assignment getDiagonalAssignment_2() { return cDiagonalAssignment_2; }
		
		//'diagonal'
		public Keyword getDiagonalDiagonalKeyword_2_0() { return cDiagonalDiagonalKeyword_2_0; }
		
		//'count'
		public Keyword getCountKeyword_3() { return cCountKeyword_3; }
		
		//count=EInt
		public Assignment getCountAssignment_4() { return cCountAssignment_4; }
		
		//EInt
		public RuleCall getCountEIntParserRuleCall_4_0() { return cCountEIntParserRuleCall_4_0; }
	}
	
	
	private final BoardGameElements pBoardGame;
	private final PieceTypeElements pPieceType;
	private final CellStateElements pCellState;
	private final WinConditionElements pWinCondition;
	private final EIntElements pEInt;
	private final EStringElements pEString;
	private final ValidMoveElements pValidMove;
	private final EffectOnCellElements pEffectOnCell;
	private final ConditionElements pCondition;
	private final EBooleanElements pEBoolean;
	private final InARowElements pInARow;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BoardGameDLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pBoardGame = new BoardGameElements();
		this.pPieceType = new PieceTypeElements();
		this.pCellState = new CellStateElements();
		this.pWinCondition = new WinConditionElements();
		this.pEInt = new EIntElements();
		this.pEString = new EStringElements();
		this.pValidMove = new ValidMoveElements();
		this.pEffectOnCell = new EffectOnCellElements();
		this.pCondition = new ConditionElements();
		this.pEBoolean = new EBooleanElements();
		this.pInARow = new InARowElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("no.ntnu.tdt4250.g07.bg.bgdl.BoardGameDL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//BoardGame returns BoardGame:
	//    'Title' (name = EString)
	//    'BoardSize' size=EInt
	//    'pieceTypes' '['piecetypes+=PieceType ( "," piecetypes+=PieceType)* ']'
	//    ('cellStates' '['cellstates+=CellState ( "," cellstates+=CellState)*']' )?
	//    'winConditions' '[' winConditions+=WinCondition ( "," winConditions+=WinCondition)* ']'
	//    ;
	public BoardGameElements getBoardGameAccess() {
		return pBoardGame;
	}
	
	public ParserRule getBoardGameRule() {
		return getBoardGameAccess().getRule();
	}
	
	//PieceType returns PieceType:
	//    'PieceType'
	//    name=EString
	//        'Symbol' symbol=EString
	//        'hasValidMovesWhen' '[' validmoves+=ValidMove ( "," validmoves+=ValidMove)* ']'
	//        ('hasEffectOnCell' '[' effectsoncell+=EffectOnCell ( "," effectsoncell+=EffectOnCell)* ']' )?;
	public PieceTypeElements getPieceTypeAccess() {
		return pPieceType;
	}
	
	public ParserRule getPieceTypeRule() {
		return getPieceTypeAccess().getRule();
	}
	
	//CellState returns CellState:
	//    name=ID
	//    ;
	public CellStateElements getCellStateAccess() {
		return pCellState;
	}
	
	public ParserRule getCellStateRule() {
		return getCellStateAccess().getRule();
	}
	
	//WinCondition returns WinCondition:
	//        'InARow' inarow=InARow;
	public WinConditionElements getWinConditionAccess() {
		return pWinCondition;
	}
	
	public ParserRule getWinConditionRule() {
		return getWinConditionAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//ValidMove returns ValidMove:
	//    'ValidMove'
	//    '{'
	//        placeAnywhere?='placeAnywhere'
	//        ('when' conditions+=Condition ( "and" conditions+=Condition)* )?
	//    '}';
	public ValidMoveElements getValidMoveAccess() {
		return pValidMove;
	}
	
	public ParserRule getValidMoveRule() {
		return getValidMoveAccess().getRule();
	}
	
	//EffectOnCell returns EffectOnCell:
	//    'effect' '->' '('
	//        'relativePosition' '('x=EInt','y=EInt')'
	//        'newCellState''('cellstate=[CellState|EString]')' ')';
	public EffectOnCellElements getEffectOnCellAccess() {
		return pEffectOnCell;
	}
	
	public ParserRule getEffectOnCellRule() {
		return getEffectOnCellAccess().getRule();
	}
	
	//Condition returns Condition:
	//        'cellstate' '->' cellstate=[CellState|EString];
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//InARow returns InARow:
	//    horizontal?='horizontal'
	//    vertical?='vertical'
	//    diagonal?='diagonal'
	//    'count' count=EInt;
	public InARowElements getInARowAccess() {
		return pInARow;
	}
	
	public ParserRule getInARowRule() {
		return getInARowAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
