/*
 * generated by Xtext 2.35.0
 */
package no.ntnu.tdt4250.g07.bg.bgdl.ui.tests;

import com.google.inject.Injector;
import no.ntnu.tdt4250.g07.bg.bgdl.ui.internal.BgdlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class BoardgameDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BgdlActivator.getInstance().getInjector("no.ntnu.tdt4250.g07.bg.bgdl.BoardgameDL");
	}

}
