/*
 * generated by Xtext 2.35.0
 */
package no.ntnu.tdt4250.g07.bg.bgdl.parser.antlr;

import com.google.inject.Inject;
import no.ntnu.tdt4250.g07.bg.bgdl.parser.antlr.internal.InternalBoardgameDLParser;
import no.ntnu.tdt4250.g07.bg.bgdl.services.BoardgameDLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BoardgameDLParser extends AbstractAntlrParser {

	@Inject
	private BoardgameDLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBoardgameDLParser createParser(XtextTokenStream stream) {
		return new InternalBoardgameDLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Rules";
	}

	public BoardgameDLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BoardgameDLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
